//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodState
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string PreserveTime { get; set; }
        public string Status { get; set; }
        public int ResId { get; set; }
        public int EmpId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Restuarant Restuarant { get; set; }
    }
}
